name: Build and test

on:
  pull_request:
    branches: ['main']
    types:
        - opened
        - reopened
        - synchronize
        - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js 14.x with yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
      
      # this step is from https://nextjs.org/docs/advanced-features/ci-build-caching
      - name: Apply Next.js build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      - name: Build the application
        run: yarn build
      
      - name: Start the server
        run: yarn start &

      - name: Run the tests
        run: yarn run codeceptjs:headless
